# Generated by Django 5.0 on 2024-01-06  18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_roomtype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='description',
            field=models.TextField(max_length=2000),
        ),
    ]
