# Generated by Django 5.0 on 2024-01-06  19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_alter_roomtype_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='type_id',
            field=models.IntegerField(default=True),
        ),
    ]
