# Generated by Django 5.0 on 2024-01-06  19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_roomtype_type_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomtype',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='type_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
